
package concesionaria.frontend.vista;

import concesionaria.backend.dtos.AutoDTO;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.util.Collection;
import javax.swing.table.DefaultTableModel;
import java.awt.Image;
import java.awt.Toolkit;


public class VistaAutos  extends VistaSwing {
private  Toolkit miPantalla=Toolkit.getDefaultToolkit();
private Image miIcono=miPantalla.getImage(getRutaImg());
 
    public VistaAutos() {
        setearIcono(miIcono);
        initComponents();
      
    }
    
      public  void limpiarTabla() {
         DefaultTableModel dtm = (DefaultTableModel) this.jTableAutos.getModel();
          for (int i = 0; i < this.jTableAutos.getRowCount();) {
            dtm.removeRow(i);

        }
    }
      
       public void agregarAutos(Collection<AutoDTO> clientes) {
        for (AutoDTO cliente : clientes) {
            agregarFila(cliente);
        }
    }

    private void agregarFila(AutoDTO d) {
        Object[] datos = {d.getID(),d.getPatente(), d.getMarca(),d.getModelo(),d.getAnio(),d.getIdCliente(),d.getProietario()};
        DefaultTableModel dtm = (DefaultTableModel) this.jTableAutos.getModel();
        dtm.addRow( datos );
    }
      public void addSeleccionarAuto(MouseListener ml) {
        this.jTableAutos.addMouseListener(ml);
    }
      
       public void setCamposAutoSeleccionado() {
        int nroFila = this.jTableAutos.getSelectedRow();
        int id = (int) this.jTableAutos.getValueAt(nroFila, 0);
        String patente = (String) this.jTableAutos.getValueAt(nroFila, 1);
        String marca = (String) this.jTableAutos.getValueAt(nroFila, 2);
        String modelo = (String) this.jTableAutos.getValueAt(nroFila, 3);
        int anio = (int) this.jTableAutos.getValueAt(nroFila, 4);
        int idCliente = (int) this.jTableAutos.getValueAt(nroFila, 5);

        this.jTextFieldId.setText("" + id);
        this.jTextFieldPatente.setText(patente);
        this.jTextFieldMarca.setText(marca);
        this.jTextFieldModelo.setText(modelo);
        this.jTextFieldAnio.setText(""+anio);
        this.jTextFieldIdCliente.setText(""+idCliente);
        this.jTextFieldCODIGOagregado.setText(""+idCliente);
    }

       public boolean getSiFilaSeleccionada(){
        return (this.jTableAutos.getSelectedRow()!=-1);
    }

       public void addAgregarAuto(ActionListener al) {
        this.jButtonAGREGAR.addActionListener(al);

    }
      
         public String[] dameDatos(){
        String[]datos={this.jTextFieldId.getText()  ,this.jTextFieldPatente.getText(),this.jTextFieldMarca.getText(),this.jTextFieldModelo.getText(),
        this.jTextFieldAnio.getText(),this.jTextFieldCODIGOagregado.getText()};
              return datos;

    }
      public void addModicarAuto(ActionListener al) {
        this.jButtonMODIFICAR.addActionListener(al);

    }
      
        public void addEliminar(ActionListener al) {
        this.jButtonELIMINAR.addActionListener(al);

    }
         public String getCodAutoSeleccionado() {
        int nroFila = this.jTableAutos.getSelectedRow();
        //return (int) this.jTableClientes.getValueAt(nroFila, 0);
        return  this.jTableAutos.getValueAt(nroFila, 0).toString();
    }
        
          public void addLimpiarAutos(ActionListener al) {
        this.jButtonLIMPIAR.addActionListener(al);

    }

    public void Setear() {
        this.jTextFieldPatente.setText("");
        this.jTextFieldMarca.setText("");
        this.jTextFieldModelo.setText("");
        this.jTextFieldAnio.setText("");
        this.jTextFieldCODIGOagregado.setText("");

    }
  public String opcionAuto() {
        String s = (String) this.jComboBoxOpcion.getSelectedItem();
        return s;
    }
    
     public void addOpcionAuto(ActionListener al) {
        this.jComboBoxOpcion.addActionListener(al);
      
             
    }
      private String getRutaImg(){
            return "src\\concesionaria\\img\\auto.png";
        }
         

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAutos = new javax.swing.JTable();
        jTextFieldId = new javax.swing.JTextField();
        jTextFieldPatente = new javax.swing.JTextField();
        jTextFieldMarca = new javax.swing.JTextField();
        jTextFieldModelo = new javax.swing.JTextField();
        jTextFieldAnio = new javax.swing.JTextField();
        jTextFieldIdCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButtonAGREGAR = new javax.swing.JButton();
        jButtonMODIFICAR = new javax.swing.JButton();
        jButtonELIMINAR = new javax.swing.JButton();
        jButtonLIMPIAR = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldCODIGOagregado = new javax.swing.JTextField();
        jComboBoxOpcion = new javax.swing.JComboBox<>();
        jLabelFONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AUTOS");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 102));
        jLabel1.setText("AUTOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 198, -1));

        jTableAutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "PATENTE", "MARCA", "MODELO", "AÑO", "COD_CLIENTE", "PROPIETARIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableAutos);
        if (jTableAutos.getColumnModel().getColumnCount() > 0) {
            jTableAutos.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTableAutos.getColumnModel().getColumn(1).setPreferredWidth(20);
            jTableAutos.getColumnModel().getColumn(2).setPreferredWidth(20);
            jTableAutos.getColumnModel().getColumn(3).setPreferredWidth(20);
            jTableAutos.getColumnModel().getColumn(4).setPreferredWidth(20);
            jTableAutos.getColumnModel().getColumn(5).setPreferredWidth(20);
            jTableAutos.getColumnModel().getColumn(6).setMinWidth(50);
            jTableAutos.getColumnModel().getColumn(6).setPreferredWidth(50);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 800, 280));

        jTextFieldId.setEditable(false);
        getContentPane().add(jTextFieldId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 111, -1));
        getContentPane().add(jTextFieldPatente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 136, -1));

        jTextFieldMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMarcaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 160, -1));
        getContentPane().add(jTextFieldModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 107, -1));

        jTextFieldAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAnioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 112, 136, 20));

        jTextFieldIdCliente.setEditable(false);
        getContentPane().add(jTextFieldIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 134, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 153));
        jLabel3.setText("PATENTE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 153));
        jLabel4.setText("MARCA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 153));
        jLabel5.setText("MODELO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 153));
        jLabel6.setText("AÑO");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 153));
        jLabel7.setText("CODIGO CLIENTE");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        jButtonAGREGAR.setText("AGREGAR");
        jButtonAGREGAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButtonAGREGAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jButtonMODIFICAR.setText("MODIFICAR");
        jButtonMODIFICAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButtonMODIFICAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        jButtonELIMINAR.setText("ELIMINAR");
        jButtonELIMINAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButtonELIMINAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, -1));

        jButtonLIMPIAR.setText("LIMPIAR");
        jButtonLIMPIAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLIMPIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLIMPIARActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLIMPIAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 95, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 153));
        jLabel8.setText("CODIGO CLIENTE (INGRESO)");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 160, -1));
        getContentPane().add(jTextFieldCODIGOagregado, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 162, -1));

        jComboBoxOpcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COMPLETO", "SELECCION", "PATENTE", "APELLIDO", "ANTIG" }));
        getContentPane().add(jComboBoxOpcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

        jLabelFONDO.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/concesionaria/img/auto3.jpg"))); // NOI18N
        getContentPane().add(jLabelFONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMarcaActionPerformed

    private void jButtonLIMPIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLIMPIARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLIMPIARActionPerformed

    private void jTextFieldAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAnioActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAGREGAR;
    private javax.swing.JButton jButtonELIMINAR;
    private javax.swing.JButton jButtonLIMPIAR;
    private javax.swing.JButton jButtonMODIFICAR;
    private javax.swing.JComboBox<String> jComboBoxOpcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelFONDO;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAutos;
    private javax.swing.JTextField jTextFieldAnio;
    private javax.swing.JTextField jTextFieldCODIGOagregado;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldIdCliente;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldModelo;
    private javax.swing.JTextField jTextFieldPatente;
    // End of variables declaration//GEN-END:variables
}
