
package concesionaria.frontend.vista;
import concesionaria.backend.dtos.ClienteDTO;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.util.Collection;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADRIAN
 */
public class VistaClientes  extends VistaSwing {
private  Toolkit miPantalla=Toolkit.getDefaultToolkit();
private Image miIcono=miPantalla.getImage(getRutaImg());

    public VistaClientes() {
        setTitle("CLIENTES");
        setearIcono(miIcono);
        initComponents();
    }


    public void agregarClientes(Collection<ClienteDTO> clientes) {
        for (ClienteDTO cliente : clientes) {
            agregarFila(cliente);
        }
    }

    private void agregarFila(ClienteDTO d) {
        Object[] datos = {d.getID(),d.getDNI(), d.getNombre(),d.getApellido(),d.getMail(),d.getTel()};
        DefaultTableModel dtm = (DefaultTableModel) this.jTableClientes.getModel();
        dtm.addRow( datos );
    }
 private String getRutaImg(){
            return "src\\concesionaria\\img\\hombre.png";
        }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldid = new javax.swing.JTextField();
        jTextFieldDNI = new javax.swing.JTextField();
        jTextFieldNOMBRE = new javax.swing.JTextField();
        jTextFieldAPELLIDO = new javax.swing.JTextField();
        jTextFieldMAIL = new javax.swing.JTextField();
        jTextFieldTE = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButtonAgregar = new javax.swing.JButton();
        jButtonMODIFICAR = new javax.swing.JButton();
        jButtonELIMINAR = new javax.swing.JButton();
        jButtonLIMPIAR = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        jLabelHombrecito = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("CLIENTES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 6, 117, 23));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "DATOS"));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("ID");

        jLabel3.setText("DNI");

        jLabel4.setText("NOMBRE");

        jLabel5.setText("APELLIDO");

        jLabel6.setText("mail");

        jLabel7.setText("TELEFONO");

        jTextFieldid.setEditable(false);
        jTextFieldid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldidActionPerformed(evt);
            }
        });

        jTextFieldNOMBRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNOMBREActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextFieldid, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldTE, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldNOMBRE)))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldAPELLIDO, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldAPELLIDO, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldTE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 40, 650, 136));
        jPanel2.getAccessibleContext().setAccessibleName("DATOS");

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("OPERACIONES"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonAgregar.setText("AGREGAR");
        jButtonAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jButtonMODIFICAR.setText("MODIFICAR");
        jButtonMODIFICAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jButtonMODIFICAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jButtonELIMINAR.setText("ELIMINAR");
        jButtonELIMINAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jButtonELIMINAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        jButtonLIMPIAR.setText("LIMPIAR");
        jButtonLIMPIAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jButtonLIMPIAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 189, 750, 59));

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DNI", "NOMBRE", "APELLIDO", "mail", "TELEFONO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableClientes);
        if (jTableClientes.getColumnModel().getColumnCount() > 0) {
            jTableClientes.getColumnModel().getColumn(0).setMinWidth(50);
            jTableClientes.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableClientes.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 276, 750, 271));

        jLabelHombrecito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/concesionaria/img/hombre.png"))); // NOI18N
        getContentPane().add(jLabelHombrecito, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 70, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldidActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jTextFieldNOMBREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNOMBREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNOMBREActionPerformed

    /**
     * @param args the command line arguments
     * eleminada main
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonELIMINAR;
    private javax.swing.JButton jButtonLIMPIAR;
    private javax.swing.JButton jButtonMODIFICAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelHombrecito;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTextField jTextFieldAPELLIDO;
    private javax.swing.JTextField jTextFieldDNI;
    private javax.swing.JTextField jTextFieldMAIL;
    private javax.swing.JTextField jTextFieldNOMBRE;
    private javax.swing.JTextField jTextFieldTE;
    private javax.swing.JTextField jTextFieldid;
    // End of variables declaration//GEN-END:variables


    //PARTE 2
    public void addMostrarAgregar(ActionListener al) {
        this.jButtonAgregar.addActionListener(al);

    }

    public String[] dameDatos() {
        String[] datos = {this.jTextFieldid.getText(), this.jTextFieldDNI.getText(), this.jTextFieldNOMBRE.getText(), this.jTextFieldAPELLIDO.getText(),
            this.jTextFieldMAIL.getText(), this.jTextFieldTE.getText()};
        return datos;
    }

    public  void limpiarTabla() {
         DefaultTableModel dtm = (DefaultTableModel) this.jTableClientes.getModel();
          for (int i = 0; i < this.jTableClientes.getRowCount();) {
            dtm.removeRow(i);

        }
    }


    public void addSeleccionarClientes(MouseListener ml) {
        this.jTableClientes.addMouseListener(ml);
    }

    public boolean getSiFilaSeleccionada(){
        return (this.jTableClientes.getSelectedRow()!=-1);
    }


    public String getCodClienteSeleccionado() {
        int nroFila = this.jTableClientes.getSelectedRow();
        return  this.jTableClientes.getValueAt(nroFila, 0).toString();
    }

    public void setCamposClienteSeleccionado() {
        int nroFila = this.jTableClientes.getSelectedRow();
        int id = (int) this.jTableClientes.getValueAt(nroFila, 0);
        String dni = (String) this.jTableClientes.getValueAt(nroFila, 1);
        String nombre = (String) this.jTableClientes.getValueAt(nroFila, 2);
        String apellido = (String) this.jTableClientes.getValueAt(nroFila, 3);
        String mail = (String) this.jTableClientes.getValueAt(nroFila, 4);
        String tel = (String) this.jTableClientes.getValueAt(nroFila, 5);

        this.jTextFieldid.setText("" + id);
        this.jTextFieldDNI.setText(dni);
        this.jTextFieldNOMBRE.setText(nombre);
        this.jTextFieldAPELLIDO.setText(apellido);
        this.jTextFieldMAIL.setText(mail);
        this.jTextFieldTE.setText(tel);
    }


    public void addModicar(ActionListener al) {
        this.jButtonMODIFICAR.addActionListener(al);

    }
    
    public void addEliminar(ActionListener al) {
        this.jButtonELIMINAR.addActionListener(al);

    }
    
     public void addLimpiar(ActionListener al) {
        this.jButtonLIMPIAR.addActionListener(al);

    }

    public void Setear() {
        this.jTextFieldDNI.setText("");
        this.jTextFieldNOMBRE.setText("");
        this.jTextFieldAPELLIDO.setText("");
        this.jTextFieldMAIL.setText("");
        this.jTextFieldTE.setText("");

    }


}
